# Generated by Django 2.0.4 on 2018-04-23 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEnhancement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verification_status', models.CharField(choices=[('EMAIL_VERIFICATION_COMPLETED', ''), ('EMAIL_VERIFICATION_IN_PROGRESS', ''), ('EMAIL_VERIFICATION_FAILED', '')], default='EMAIL_VERIFICATION_FAILED', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enhancement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
